[2023-03-13 22:15:02,015] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.is_api_available scheduled__2023-03-13T22:10:00+00:00 [queued]>
[2023-03-13 22:15:02,021] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.is_api_available scheduled__2023-03-13T22:10:00+00:00 [queued]>
[2023-03-13 22:15:02,022] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 22:15:02,022] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-13 22:15:02,023] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 22:15:02,034] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-03-13 22:10:00+00:00
[2023-03-13 22:15:02,047] {standard_task_runner.py:52} INFO - Started process 7551 to run task
[2023-03-13 22:15:02,054] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'is_api_available', 'scheduled__2023-03-13T22:10:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpm1djdkwr', '--error-file', '/tmp/tmp_e6ns9lr']
[2023-03-13 22:15:02,055] {standard_task_runner.py:80} INFO - Job 144: Subtask is_api_available
[2023-03-13 22:15:02,210] {task_command.py:369} INFO - Running <TaskInstance: test.is_api_available scheduled__2023-03-13T22:10:00+00:00 [running]> on host 5282528dd996
[2023-03-13 22:15:02,284] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T22:10:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T22:10:00+00:00
[2023-03-13 22:15:02,286] {http.py:97} INFO - Poking: api/
[2023-03-13 22:15:02,294] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2023-03-13 22:15:02,296] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-03-13 22:15:02,475] {base.py:301} INFO - Success criteria met. Exiting.
[2023-03-13 22:15:02,490] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test, task_id=is_api_available, execution_date=20230313T221000, start_date=20230313T221502, end_date=20230313T221502
[2023-03-13 22:15:02,517] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-13 22:15:02,564] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
