[2023-03-13 22:30:02,642] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.is_api_available scheduled__2023-03-13T22:25:00+00:00 [queued]>
[2023-03-13 22:30:02,647] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.is_api_available scheduled__2023-03-13T22:25:00+00:00 [queued]>
[2023-03-13 22:30:02,647] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 22:30:02,648] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-13 22:30:02,648] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 22:30:02,655] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-03-13 22:25:00+00:00
[2023-03-13 22:30:02,659] {standard_task_runner.py:52} INFO - Started process 8327 to run task
[2023-03-13 22:30:02,662] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'is_api_available', 'scheduled__2023-03-13T22:25:00+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpe8fvm2yv', '--error-file', '/tmp/tmpk8o6wl2u']
[2023-03-13 22:30:02,663] {standard_task_runner.py:80} INFO - Job 159: Subtask is_api_available
[2023-03-13 22:30:02,704] {task_command.py:369} INFO - Running <TaskInstance: test.is_api_available scheduled__2023-03-13T22:25:00+00:00 [running]> on host 5282528dd996
[2023-03-13 22:30:02,750] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T22:25:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T22:25:00+00:00
[2023-03-13 22:30:02,751] {http.py:97} INFO - Poking: api/
[2023-03-13 22:30:02,760] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2023-03-13 22:30:02,762] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-03-13 22:30:02,929] {base.py:301} INFO - Success criteria met. Exiting.
[2023-03-13 22:30:02,945] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test, task_id=is_api_available, execution_date=20230313T222500, start_date=20230313T223002, end_date=20230313T223002
[2023-03-13 22:30:03,002] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-13 22:30:03,040] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
