[2023-03-13 21:04:57,697] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.is_api_available manual__2023-03-13T21:04:49.567312+00:00 [queued]>
[2023-03-13 21:04:57,706] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.is_api_available manual__2023-03-13T21:04:49.567312+00:00 [queued]>
[2023-03-13 21:04:57,707] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 21:04:57,707] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-13 21:04:57,707] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 21:04:57,731] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-03-13 21:04:49.567312+00:00
[2023-03-13 21:04:57,747] {standard_task_runner.py:52} INFO - Started process 4026 to run task
[2023-03-13 21:04:57,765] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'is_api_available', 'manual__2023-03-13T21:04:49.567312+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp3mwe9rj0', '--error-file', '/tmp/tmpc3jv_eds']
[2023-03-13 21:04:57,769] {standard_task_runner.py:80} INFO - Job 81: Subtask is_api_available
[2023-03-13 21:04:57,889] {task_command.py:369} INFO - Running <TaskInstance: test.is_api_available manual__2023-03-13T21:04:49.567312+00:00 [running]> on host 5282528dd996
[2023-03-13 21:04:58,232] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T21:04:49.567312+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-13T21:04:49.567312+00:00
[2023-03-13 21:04:58,242] {http.py:97} INFO - Poking: api/
[2023-03-13 21:04:58,332] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2023-03-13 21:04:58,351] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-03-13 21:04:58,653] {base.py:301} INFO - Success criteria met. Exiting.
[2023-03-13 21:04:58,714] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test, task_id=is_api_available, execution_date=20230313T210449, start_date=20230313T210457, end_date=20230313T210458
[2023-03-13 21:04:58,776] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-13 21:04:58,857] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
